#!/usr/bin/env python3
"""
Downloads JS/CSS assets and patches the ASSET BUNDLE block in assets.py.
Run once: python fetch_assets.py
"""
import urllib.request
import os
import re
import sys

CDNJS = 'https://cdnjs.cloudflare.com/ajax/libs'

URLS = {
    'MARKDOWN_IT_JS': f'{CDNJS}/markdown-it/13.0.2/markdown-it.min.js',
    'HLJS_JS':        f'{CDNJS}/highlight.js/11.9.0/highlight.min.js',
}

THEME_URLS = {
    'github-dark':    f'{CDNJS}/highlight.js/11.9.0/styles/github-dark.min.css',
    'github':         f'{CDNJS}/highlight.js/11.9.0/styles/github.min.css',
    'dracula':        f'{CDNJS}/highlight.js/11.9.0/styles/base16/dracula.min.css',
    'monokai':        f'{CDNJS}/highlight.js/11.9.0/styles/monokai.min.css',
    'nord':           f'{CDNJS}/highlight.js/11.9.0/styles/nord.min.css',
    'atom-one-dark':  f'{CDNJS}/highlight.js/11.9.0/styles/atom-one-dark.min.css',
    'solarized-dark': f'{CDNJS}/highlight.js/11.9.0/styles/base16/solarized-dark.min.css',
    'vs2015':         f'{CDNJS}/highlight.js/11.9.0/styles/vs2015.min.css',
}


def fetch(url: str) -> str:
    print(f'  GET {url}')
    with urllib.request.urlopen(url, timeout=15) as r:
        return r.read().decode('utf-8')


print('Fetching assets...')
assets = {name: fetch(url) for name, url in URLS.items()}

themes = {}
for key, url in THEME_URLS.items():
    try:
        themes[key] = fetch(url)
    except Exception as e:
        print(f'  WARNING: failed to fetch {key} from {url}: {e}')
        if key == 'solarized-dark':
            fallback_url = f'{CDNJS}/highlight.js/11.9.0/styles/atom-one-dark.min.css'
            print(f'  Falling back to atom-one-dark for solarized-dark slot')
            themes[key] = fetch(fallback_url)
        else:
            raise

lines = [
    '# -- ASSET BUNDLE (generated by fetch_assets.py) ----------------------------',
]
for name, content in assets.items():
    # Use base64 encoding to avoid escape sequence issues in triple-quoted strings
    import base64
    b64 = base64.b64encode(content.encode('utf-8')).decode('ascii')
    lines.append(f'{name} = __import__("base64").b64decode("{b64}").decode("utf-8")')

lines.append('HLJS_THEMES = {')
for key, css in themes.items():
    import base64
    b64 = base64.b64encode(css.encode('utf-8')).decode('ascii')
    lines.append(f'    {key!r}: __import__("base64").b64decode("{b64}").decode("utf-8"),')
lines.append('}')
lines.append('# -- END ASSET BUNDLE -----------------------------------------------')

replacement = '\n'.join(lines)

target = os.path.join(os.path.dirname(__file__), 'assets.py')
with open(target, 'r', encoding='utf-8') as f:
    src = f.read()

pattern = r'# -- ASSET BUNDLE.*?# -- END ASSET BUNDLE -+\n?'
if not re.search(pattern, src, re.DOTALL):
    print('ERROR: sentinel block not found in assets.py')
    sys.exit(1)

src = re.sub(pattern, replacement + '\n', src, flags=re.DOTALL)

with open(target, 'w', encoding='utf-8') as f:
    f.write(src)

print(f'Done. Patched {target}')
